# =========================
# Experiment configurations
# =========================
defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_


hydra:

  # adds colorlog to logging
  job_logging:
    formatters:
      colorlog:
        format: '[%(cyan)s%(asctime)s%(reset)s][%(blue)s%(name)s%(reset)s][%(log_color)s%(levelname)s%(reset)s] - %(message)s'
        log_colors:
          DEBUG: purple
          INFO: green
          WARNING: yellow
          ERROR: red
          CRITICAL: bold_red

  # tells hydra to make the run/dir the current working director
  job:
    chdir: true

  # folder structure
  run:
    dir: ./outputs/model_eval/${out_path}
  sweep:
    dir: ./outputs/multirun/model_eval
    subdir: ${out_path}_${hydra.job.id}


run_path: '???'
out_path: ${get_folder_name:${run_path}}_${checkpoint}_${now:%Y-%m-%d}T${now:%H-%M-%S}

# These are automatically set for you
data_path: /home/pl487/rdd/data/minipile-eval

# Set here
checkpoint: last

seed: 42

# model config
accelerator: gpu
precision: bf16-true
tf32_mode: high
torch_compile: false

# data config
batch_size: 128
multiprocessing_context: null
write_interval: 10
only_sequence_surprisal: false