lr_monitor:
  _target_: src.callbacks.lr_monitor.SimpleLearningRateMonitor 
  # _target_: lightning.pytorch.callbacks.LearningRateMonitor
  # logging_interval: step
  # log_momentum: false
  # log_weight_decay: false